# Generated by Django 4.1.4 on 2023-01-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senedtap_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
    ]
