# Generated by Django 4.1.4 on 2023-01-12 17:47

from django.db import migrations, models
import senedtap_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('senedtap_api', '0003_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=senedtap_api.models.upload_to)),
            ],
        ),
    ]
