# Generated by Django 4.1.4 on 2023-01-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senedtap_api', '0006_companies_docs_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
