# Generated by Django 4.1.4 on 2023-02-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senedtap_api', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
